export const DEPARTMENTS = [
  "All Departments",
  "Commissioner Office",
  "Administration",
  "Health",
  "Engineering",
  "Water Supply",
  "Drainage",
  "Solid Waste Management",
  "Fire & Emergency Services",
  "Town Planning",
  "Estate",
  "Revenue",
  "Urban Community Development",
  "Housing",
  "Garden",
  "Information Technology",
  "Accounts & Finance",
  "Legal",
  "Education",
  "Zoo",
  "Library",
  "Sports",
  "Disaster Management",
  "Procurement",
  "Public Grievance",
] as const;

export type Department = (typeof DEPARTMENTS)[number];
