/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as Org360RouteImport } from './routes/org360'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OcrScannerRouteImport } from './routes/ocr-scanner'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as GrievancesRouteImport } from './routes/grievances'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as MyTaxRegimeRouteImport } from './routes/my.tax-regime'
import { Route as MyTasksRouteImport } from './routes/my.tasks'
import { Route as MyPrivacyRequestsRouteImport } from './routes/my.privacy-requests'
import { Route as MyPayslipRouteImport } from './routes/my.payslip'
import { Route as MyLeaveRouteImport } from './routes/my.leave'
import { Route as MyGrievancesRouteImport } from './routes/my.grievances'
import { Route as MyAttendanceRouteImport } from './routes/my.attendance'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const Org360Route = Org360RouteImport.update({
  id: '/org360',
  path: '/org360',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrScannerRoute = OcrScannerRouteImport.update({
  id: '/ocr-scanner',
  path: '/ocr-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancesRoute = GrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const MyTaxRegimeRoute = MyTaxRegimeRouteImport.update({
  id: '/tax-regime',
  path: '/tax-regime',
  getParentRoute: () => MyRoute,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => MyRoute,
} as any)
const MyPrivacyRequestsRoute = MyPrivacyRequestsRouteImport.update({
  id: '/privacy-requests',
  path: '/privacy-requests',
  getParentRoute: () => MyRoute,
} as any)
const MyPayslipRoute = MyPayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => MyRoute,
} as any)
const MyLeaveRoute = MyLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => MyRoute,
} as any)
const MyGrievancesRoute = MyGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => MyRoute,
} as any)
const MyAttendanceRoute = MyAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MyRoute,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/copilot': typeof CopilotRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/finance': typeof FinanceRoute
  '/grievances': typeof GrievancesRoute
  '/leave': typeof LeaveRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/ocr-scanner': typeof OcrScannerRoute
  '/onboarding': typeof OnboardingRoute
  '/org360': typeof Org360Route
  '/privacy': typeof PrivacyRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/my/attendance': typeof MyAttendanceRoute
  '/my/grievances': typeof MyGrievancesRoute
  '/my/leave': typeof MyLeaveRoute
  '/my/payslip': typeof MyPayslipRoute
  '/my/privacy-requests': typeof MyPrivacyRequestsRoute
  '/my/tasks': typeof MyTasksRoute
  '/my/tax-regime': typeof MyTaxRegimeRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/copilot': typeof CopilotRoute
  '/finance': typeof FinanceRoute
  '/grievances': typeof GrievancesRoute
  '/leave': typeof LeaveRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/ocr-scanner': typeof OcrScannerRoute
  '/onboarding': typeof OnboardingRoute
  '/org360': typeof Org360Route
  '/privacy': typeof PrivacyRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/my/attendance': typeof MyAttendanceRoute
  '/my/grievances': typeof MyGrievancesRoute
  '/my/leave': typeof MyLeaveRoute
  '/my/payslip': typeof MyPayslipRoute
  '/my/privacy-requests': typeof MyPrivacyRequestsRoute
  '/my/tasks': typeof MyTasksRoute
  '/my/tax-regime': typeof MyTaxRegimeRoute
  '/employees': typeof EmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/copilot': typeof CopilotRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/finance': typeof FinanceRoute
  '/grievances': typeof GrievancesRoute
  '/leave': typeof LeaveRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/ocr-scanner': typeof OcrScannerRoute
  '/onboarding': typeof OnboardingRoute
  '/org360': typeof Org360Route
  '/privacy': typeof PrivacyRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/employees/$id': typeof EmployeesIdRoute
  '/my/attendance': typeof MyAttendanceRoute
  '/my/grievances': typeof MyGrievancesRoute
  '/my/leave': typeof MyLeaveRoute
  '/my/payslip': typeof MyPayslipRoute
  '/my/privacy-requests': typeof MyPrivacyRequestsRoute
  '/my/tasks': typeof MyTasksRoute
  '/my/tax-regime': typeof MyTaxRegimeRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/copilot'
    | '/employees'
    | '/finance'
    | '/grievances'
    | '/leave'
    | '/legal'
    | '/login'
    | '/my'
    | '/ocr-scanner'
    | '/onboarding'
    | '/org360'
    | '/privacy'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/employees/$id'
    | '/my/attendance'
    | '/my/grievances'
    | '/my/leave'
    | '/my/payslip'
    | '/my/privacy-requests'
    | '/my/tasks'
    | '/my/tax-regime'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/copilot'
    | '/finance'
    | '/grievances'
    | '/leave'
    | '/legal'
    | '/login'
    | '/my'
    | '/ocr-scanner'
    | '/onboarding'
    | '/org360'
    | '/privacy'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/employees/$id'
    | '/my/attendance'
    | '/my/grievances'
    | '/my/leave'
    | '/my/payslip'
    | '/my/privacy-requests'
    | '/my/tasks'
    | '/my/tax-regime'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/copilot'
    | '/employees'
    | '/finance'
    | '/grievances'
    | '/leave'
    | '/legal'
    | '/login'
    | '/my'
    | '/ocr-scanner'
    | '/onboarding'
    | '/org360'
    | '/privacy'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/employees/$id'
    | '/my/attendance'
    | '/my/grievances'
    | '/my/leave'
    | '/my/payslip'
    | '/my/privacy-requests'
    | '/my/tasks'
    | '/my/tax-regime'
    | '/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  CopilotRoute: typeof CopilotRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  GrievancesRoute: typeof GrievancesRoute
  LeaveRoute: typeof LeaveRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRouteWithChildren
  OcrScannerRoute: typeof OcrScannerRoute
  OnboardingRoute: typeof OnboardingRoute
  Org360Route: typeof Org360Route
  PrivacyRoute: typeof PrivacyRoute
  RecruitmentRoute: typeof RecruitmentRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org360': {
      id: '/org360'
      path: '/org360'
      fullPath: '/org360'
      preLoaderRoute: typeof Org360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-scanner': {
      id: '/ocr-scanner'
      path: '/ocr-scanner'
      fullPath: '/ocr-scanner'
      preLoaderRoute: typeof OcrScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievances': {
      id: '/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof GrievancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/my/tax-regime': {
      id: '/my/tax-regime'
      path: '/tax-regime'
      fullPath: '/my/tax-regime'
      preLoaderRoute: typeof MyTaxRegimeRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/tasks': {
      id: '/my/tasks'
      path: '/tasks'
      fullPath: '/my/tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/privacy-requests': {
      id: '/my/privacy-requests'
      path: '/privacy-requests'
      fullPath: '/my/privacy-requests'
      preLoaderRoute: typeof MyPrivacyRequestsRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/payslip': {
      id: '/my/payslip'
      path: '/payslip'
      fullPath: '/my/payslip'
      preLoaderRoute: typeof MyPayslipRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/leave': {
      id: '/my/leave'
      path: '/leave'
      fullPath: '/my/leave'
      preLoaderRoute: typeof MyLeaveRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/grievances': {
      id: '/my/grievances'
      path: '/grievances'
      fullPath: '/my/grievances'
      preLoaderRoute: typeof MyGrievancesRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/attendance': {
      id: '/my/attendance'
      path: '/attendance'
      fullPath: '/my/attendance'
      preLoaderRoute: typeof MyAttendanceRouteImport
      parentRoute: typeof MyRoute
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
  }
}

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface MyRouteChildren {
  MyAttendanceRoute: typeof MyAttendanceRoute
  MyGrievancesRoute: typeof MyGrievancesRoute
  MyLeaveRoute: typeof MyLeaveRoute
  MyPayslipRoute: typeof MyPayslipRoute
  MyPrivacyRequestsRoute: typeof MyPrivacyRequestsRoute
  MyTasksRoute: typeof MyTasksRoute
  MyTaxRegimeRoute: typeof MyTaxRegimeRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyAttendanceRoute: MyAttendanceRoute,
  MyGrievancesRoute: MyGrievancesRoute,
  MyLeaveRoute: MyLeaveRoute,
  MyPayslipRoute: MyPayslipRoute,
  MyPrivacyRequestsRoute: MyPrivacyRequestsRoute,
  MyTasksRoute: MyTasksRoute,
  MyTaxRegimeRoute: MyTaxRegimeRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  CopilotRoute: CopilotRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  FinanceRoute: FinanceRoute,
  GrievancesRoute: GrievancesRoute,
  LeaveRoute: LeaveRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRouteWithChildren,
  OcrScannerRoute: OcrScannerRoute,
  OnboardingRoute: OnboardingRoute,
  Org360Route: Org360Route,
  PrivacyRoute: PrivacyRoute,
  RecruitmentRoute: RecruitmentRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
